# Generated by Django 5.1.6 on 2025-03-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cart_order_product_delete_medicalequipment_and_more'),
    ]

    operations = [
    ]
