# Generated by Django 5.2.1 on 2025-05-20 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_total_price_alter_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=10, verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=36, null=True, verbose_name='Payment ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_order_id',
            field=models.CharField(max_length=40, null=True, verbose_name='Order ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='signature_id',
            field=models.CharField(max_length=128, null=True, verbose_name='Signature ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=254, verbose_name='Payment Status'),
        ),
    ]
