# Generated by Django 5.2.1 on 2025-05-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
