# Generated by Django 6.0.4 on 2026-04-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cartitem_added_at_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, default='https://via.placeholder.com/150'),
        ),
    ]
